### ISSUE TITLE
Handle vanity URLs

### ISSUE THREAD

**Issue by adgad** [Financial-Times/ads-api#8]
If a stream has a vanity URL (e.g. next.ft.com/technology or whatever) it should still be recognised as a stream page.

We can use https://github.com/Financial-Times/n-url-management-api-read-client to map the referrer URL to it's original.

/cc @matthew-andrews

**Comment by matthew-andrews** [comment]
yes

**Comment by matthew-andrews** [comment]
let me know if/when you need access keys :key:

**Comment by adgad** [comment]
Resolved by https://github.com/Financial-Times/next-ads-api/pull/23
